Build Error: pow_tests
Fixes Error in multiple test cases in pow_tests
 error: too few arguments to function ‘unsigned int CalculateNextWorkRequired

Needs further review and test data needs to be updated. 
This commit creates warnings 
test/pow_tests.cpp:28:48: warning: ‘nInterval’ is used uninitialized in this function [-Wuninitialized]